### ISSUE TITLE
Sub to different products sharing same original_transaction_id

### ISSUE THREAD

**Issue by exklamationmark** [exklm/iosiap#34]
Some receipt verification result shows 2 different product_id sharing the same `original_transaction_id`.

This doesn't match with earlier observation, where subscription to different `product_id`s have different `original_transaction_id`s.

This will cause `GetSubscriptions` to group both into the same group, though they doesn't seem related.

NOTE: the `xxxxx` part is redacted, but basically both `original_transaction_id` are the same.

```
 {
 	"quantity": "1",
 	"product_id": "com.viki.subscription.vikipass2016.1month",
 	"transaction_id": "xxxxx76761",
 	"original_transaction_id": "xxxxx07640",
 	"purchase_date": "2016-12-06 05:02:53 Etc/GMT",
 	"purchase_date_ms": "1481000573000",
 	"purchase_date_pst": "2016-12-05 21:02:53 America/Los_Angeles",
 	"original_purchase_date": "2016-12-05 23:02:56 Etc/GMT",
 	"original_purchase_date_ms": "1480978976000",
 	"original_purchase_date_pst": "2016-12-05 15:02:56 America/Los_Angeles",
 	"expires_date": "2017-01-06 05:02:53 Etc/GMT",
 	"expires_date_ms": "1483678973000",
 	"expires_date_pst": "2017-01-05 21:02:53 America/Los_Angeles",
 	"web_order_line_item_id": "xxxxx54202",
 	"is_trial_period": "false"
 }, {
 	"quantity": "1",
 	"product_id": "com.viki.subscription.vikipass2016.12months",
 	"transaction_id": "xxxxx91531",
 	"original_transaction_id": "xxxxx07640",
 	"purchase_date": "2017-01-06 05:02:53 Etc/GMT",
 	"purchase_date_ms": "1483678973000",
 	"purchase_date_pst": "2017-01-05 21:02:53 America/Los_Angeles",
 	"original_purchase_date": "2017-01-05 23:02:56 Etc/GMT",
 	"original_purchase_date_ms": "1483657376225",
 	"original_purchase_date_pst": "2017-01-05 15:02:56 America/Los_Angeles",
 	"expires_date": "2018-01-06 05:02:53 Etc/GMT",
 	"expires_date_ms": "1515214973000",
 	"expires_date_pst": "2018-01-05 21:02:53 America/Los_Angeles",
 	"web_order_line_item_id": xxxxx84030 ",
 	"is_trial_period": "false"
 }
```

Thoughts:

- Try and see if Apple has anything to say about this. On dashboard, the 2 products are in the same subscription groups, so this might be an upgrade/downgrade event (see <http://devstreaming.apple.com/videos/wwdc/2016/301fbtjd9exjetky78s/301/301_introducing_expanded_subscriptions_in_itunes_connect.pdf>). If so, some modelling need to be updated.
However since the 12-month is purchased right at the time the 1-month end, it seems more of a renewal than immediate upgrade

- If it's a bug, a workaround might be using an extra field to segregate subscriptions to different products

**Comment by exklm** [comment]
confirmed that this was caused by subscription in the same group upgrading.
Therefore, the primary key to identify an actual subscription is now `(originalTransactionID, productID)`.

This should be reflected in the `GetSubscriptions()` call
